Repository wecode-bootcamp-korea/46-1st-Code200-backend, pull requests merged in 2023-06, with the labels that each got.

#4 [김상우]ADD: 제품 상세조회 기능 추가 완료
  controllers/productController.js
  db/migrations/20230601071118_modify_column.sql
  models/dataSource.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
Labels: 완료

#9 [전승한]signup,signin 기능구현완료
  .gitignore
  app.js
  controllers/userController.js
  middleware/auth.js
  middleware/error.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/userRouter.js
  services/userService.js
Labels: 멘토 리뷰 요청, 수정 요청

#11 [46전승한 ]categories 조회 api구현
  controllers/categoryController.js
  models/categoryDao.js
  routes/categoryRouter.js
  routes/index.js
  routes/userRouter.js
  services/categoryService.js
  services/userService.js
Labels: 멘토 리뷰 요청

#13 [46th 전승한]로그인 중복 기능구현
  app.js
  controllers/userController.js
  middleware/auth.js
  middleware/error.js
  middleware/validation.js
  models/userDao.js
  routes/userRouter.js
  services/userService.js
Labels: 수정 요청

#14 [김상우] ADD: 좋아요 기능 구현
  controllers/likeController.js
  controllers/productController.js
  models/cartDao.js
  models/likeDao.js
  models/productDao.js
  routes/index.js
  routes/likeRouter.js
  services/cartService.js
  services/likeService.js
Labels: 멘토 리뷰 요청

#6 [김상우] ADD: review 기능 구현 완료
  controllers/productController.js
  controllers/reviewController.js
  middleware/auth.js
  models/productDao.js
  models/reviewDao.js
  routes/index.js
  routes/productRouter.js
  routes/reviewRouter.js
  services/productService.js
  services/reviewService.js
Labels: 멘토 리뷰 요청

#15 [하진희] 상품리스트, 정렬, 필터, 페이지네이션 구현
  controllers/productController.js
  middleware/error.js
  models/productDao.js
  models/queryBuilder.js
  routes/productRouter.js
  services/productService.js
Labels: 수정 요청

#16 [김상우]FIX: product detail 수정완료 (feature/likes)
  models/productDao.js
  services/productService.js
Labels: 멘토 리뷰 요청

#19 [김상우] like항목추가&cart생성 구현 완료
  controllers/cartController.js
  controllers/productController.js
  middleware/auth.js
  models/cartDao.js
  models/productDao.js
  routes/cartRouter.js
  routes/productRouter.js
  services/cartService.js
  services/productService.js
Labels: 멘토 리뷰 요청
